In [1]:
import torch, torch.nn as nn

In [5]:
tens = torch.randn(3, 5)

In [17]:
tens

tensor([[ 1.7967, -0.4893, -1.3782, -1.6285, -0.0757],
        [ 0.0369,  0.1075,  0.7496,  0.3100, -0.3952],
        [ 0.4015, -2.1589, -0.3946, -0.1528, -1.6630]])

In [21]:
def function1(tensor: torch.Tensor, count_over: str):
    if count_over == 'columns':
        return torch.sum(tensor, dim=1)
    if count_over == 'row':
        return torch.sum(tensor, dim=0)
function1(tens, 'row'), function1(tens, 'columns')

(tensor([ 2.2350, -2.5407, -1.0232, -1.4713, -2.1338]),
 tensor([-1.7750,  0.8088, -3.9678]))

In [69]:

def function2():
    w = torch.randn(2, dtype=torch.float32, requires_grad=True)
    return w
    
    

In [49]:
n_features = 2
n_objects = 300

w_true = torch.randn(n_features)
X = (torch.rand(n_objects, n_features) - 0.5) * 5
Y = X @ w_true + torch.randn(n_objects) / 2


In [71]:
def function3(X: torch.Tensor, Y: torch.Tensor):
    w = function2()
    step = 1e-2
    n_steps = 200  
    for i in range(n_steps):
        y_pred = X @ w
        mse = torch.mean((Y - y_pred)**2)
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')
        mse.backward()
        with torch.no_grad():
            w -= w.grad * step
        w.grad.zero_()
    return w
function3(X, Y)

        
    
    

MSE на шаге 1 19.75664
MSE на шаге 2 18.14849
MSE на шаге 3 16.67365
MSE на шаге 4 15.32103
MSE на шаге 5 14.08044
MSE на шаге 6 12.94257
MSE на шаге 7 11.89889
MSE на шаге 8 10.94155
MSE на шаге 9 10.06339
MSE на шаге 10 9.25782
MSE на шаге 11 8.51882
MSE на шаге 12 7.84087
MSE на шаге 13 7.21890
MSE на шаге 14 6.64826
MSE на шаге 15 6.12470
MSE на шаге 16 5.64432
MSE на шаге 17 5.20354
MSE на шаге 18 4.79908
MSE на шаге 19 4.42794
MSE на шаге 20 4.08735
MSE на шаге 21 3.77479
MSE на шаге 22 3.48795
MSE на шаге 23 3.22470
MSE на шаге 24 2.98308
MSE на шаге 25 2.76132
MSE на шаге 26 2.55777
MSE на шаге 27 2.37093
MSE на шаге 28 2.19942
MSE на шаге 29 2.04198
MSE на шаге 30 1.89745
MSE на шаге 31 1.76476
MSE на шаге 32 1.64294
MSE на шаге 33 1.53110
MSE на шаге 34 1.42841
MSE на шаге 35 1.33412
MSE на шаге 36 1.24755
MSE на шаге 37 1.16805
MSE на шаге 38 1.09505
MSE на шаге 39 1.02801
MSE на шаге 40 0.96644
MSE на шаге 41 0.90989
MSE на шаге 42 0.85796
MSE на шаге 43 0.81026
MSE на шаге

tensor([ 1.6747, -1.4983], requires_grad=True)

In [77]:
def function4(X: torch.Tensor, Y: torch.Tensor):
    w = function2()
    step = 1e-2
    n_steps = 200
    layer = nn.Linear(in_features=2, out_features=1)
    for i in range(n_steps):
        y_pred = layer(X).ravel()
        mse = torch.mean((Y - y_pred)**2)
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')
        mse.backward()
        with torch.no_grad():
            layer.weight -= layer.weight.grad * step
            layer.bias -= layer.bias.grad * step
        layer.zero_grad()
    return layer
function4(X, Y)

MSE на шаге 1 11.87686
MSE на шаге 2 10.88322
MSE на шаге 3 9.97514
MSE на шаге 4 9.14523
MSE на шаге 5 8.38673
MSE на шаге 6 7.69347
MSE на шаге 7 7.05983
MSE на шаге 8 6.48065
MSE на шаге 9 5.95123
MSE на шаге 10 5.46729
MSE на шаге 11 5.02489
MSE на шаге 12 4.62045
MSE на шаге 13 4.25071
MSE на шаге 14 3.91266
MSE на шаге 15 3.60359
MSE на шаге 16 3.32098
MSE на шаге 17 3.06257
MSE на шаге 18 2.82627
MSE на шаге 19 2.61018
MSE на шаге 20 2.41255
MSE на шаге 21 2.23180
MSE на шаге 22 2.06648
MSE на шаге 23 1.91527
MSE на шаге 24 1.77694
MSE на шаге 25 1.65039
MSE на шаге 26 1.53462
MSE на шаге 27 1.42869
MSE на шаге 28 1.33176
MSE на шаге 29 1.24307
MSE на шаге 30 1.16190
MSE на шаге 31 1.08761
MSE на шаге 32 1.01961
MSE на шаге 33 0.95736
MSE на шаге 34 0.90037
MSE на шаге 35 0.84819
MSE на шаге 36 0.80042
MSE на шаге 37 0.75666
MSE на шаге 38 0.71659
MSE на шаге 39 0.67989
MSE на шаге 40 0.64626
MSE на шаге 41 0.61545
MSE на шаге 42 0.58722
MSE на шаге 43 0.56135
MSE на шаге 44 0.5

Linear(in_features=2, out_features=1, bias=True)